---
name: Reusable Linting
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      language:
        required: true
        type: string
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
        if: inputs.language == 'shell'
        with:
          python-version: '3.11'
      - name: shellcheck
        if: inputs.language == 'shell'
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
        with:
          extra_args: shellcheck --all-files
      - name: shfmt
        if: inputs.language == 'shell'
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
        with:
          extra_args: shfmt --all-files
      - name: Lua Lint
        if: inputs.language == 'lua'
        uses: lunarmodules/luacheck@cc089e3f65acdd1ef8716cc73a3eca24a6b845e4  # v1
        with:
          args: ${{ inputs.working-directory }}
      - name: YAML/JSON Lint
        if: inputs.language == 'yaml' || inputs.language == 'json'
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c  # v3
        with:
          file_or_dir: ${{ inputs.working-directory }}
